;Escribir un programa que imprime “INGENIERIA E INFORMATICA” en la impresora a través del
;HAND-SHAKE. La comunicación se establece por consulta de estado (polling). 

HAND_DATO EQU 40H
HAND_ESTADO EQU 41H

ORG 1000H
MSJ DB "INGENIERIA E INFORMATICA"
FIN DB ?

ORG 2000H
;CONFIG HAND SHAKE 
IN AL,HAND_ESTADO
AND AL, 01111111B
OUT HAND_ESTADO,AL
;
;RECORRER MENSAJE
MOV BX, OFFSET MSJ
POLL: IN AL, HAND_ESTADO
AND AL,1 ; 00000001
JNZ POLL
MOV AL,[BX]
OUT HAND_DATO,AL
INC BX
CMP BX, OFFSET FIN
JNZ POLL
INT 0
END
