;Escribir un programa que imprime “UNIVERSIDAD NACIONAL DE LA PLATA” en la impresora a
;través del HAND-SHAKE. La comunicación se establece por interrupciones emitidas desde el
;HAND-SHAKE cada vez que la impresora se desocupa 
EOI EQU 20H
IMR EQU 21H
INT2 EQU 26H

HAND_DATO EQU 40H
HAND_ESTADO EQU 41H

ORG 36
ID_IMPRIMIR DW RUT_IMPRIMIR

ORG 1000H
MSJ DB "UNIVERSIDAD NACIONAL DE LA PLATA"
FIN DB ?

ORG 3000H
RUT_IMPRIMIR: PUSH AX
MOV AL,[BX]
OUT HAND_DATO,AL
INC BX

MOV AL, EOI
OUT EOI,AL
POP AX
IRET

ORG 2000H
MOV AX,RUT_IMPRIMIR
MOV BX,OFFSET ID_IMPRIMIR
MOV [BX],AX
;PIC
CLI
MOV AL,11111011B
OUT IMR,AL
MOV AL,9
OUT INT2,AL
STI

MOV BX, OFFSET MSJ
;CONFIG INTERRUPCION
IN AL,HAND_ESTADO
OR AL,10000000B
OUT HAND_ESTADO,AL

POLL: CMP BX,OFFSET FIN
      JNZ POLL

; DESACTIVAR HANDSHAKE 
IN AL, HAND_ESTADO
AND AL,011111111B
OUT HAND_ESTADO,AL

INT 0 
END
